### ISSUE TITLE
宣言が抜けている気がします。

### ISSUE THREAD

**Issue by 5atk6** [lastaflute/lastaflute-example-harbor#2]
チュートリアル(http://dbflute.seasar.org/ja/lastaflute/howto/action/makeashtml.html#roughfinished)の「ラフスケッチできた」のコードについてです。
以下の宣言が抜けている気がします。
Integer userId = getUserBean().get().getUserId();
これがないと、エラーが出てしまいました。

**Comment by jflute** [comment]
おおおぉ、ありがとうございます。
直しました！

http://dbflute.seasar.org/ja/lastaflute/howto/action/makeashtml.html#roughfinished

**Comment by 5atk6** [comment]
ありがとうございます。
